/*
 * Created on 2004-6-13
 *
 * To change the template for this generated file go to
 * Window - Preferences - Java - Code Generation - Code and Comments
 */
package com.servlet;

import java.io.IOException;
import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.PrintWriter;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author haoyulong
 *
 * To change the template for this generated type comment go to
 * Window - Preferences - Java - Code Generation - Code and Comments
 */
public class LoginCheck extends HttpServlet {
	protected void processRequest(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException,SQLException, Exception {
	
		String username=request.getParameter("uname");
		String password=request.getParameter("pass");
               
                java.sql.Connection conn=null;
	       java.sql.Statement st=null;//语句对象
	      java.sql.ResultSet rs=null;//结果集对象
               PrintWriter out = response.getWriter();
		
              try {
		Class.forName("com.mysql.jdbc.Driver");
         
                conn=java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/boyuebbs","root","0000");
                st=conn.createStatement();  //建立语句对象
                       
                String sql="select id,pwd,nickname from user";  //SQL语句根据需要改--------------------------------
             
                rs=st.executeQuery(sql);//这里
               boolean flog=false;
                while(rs.next()){
                   if(username.equals(rs.getString("id"))&&password.equals(rs.getString("pwd"))){
                        flog=true;
                        
                        HttpSession session = request.getSession();
                        session.setAttribute("usernam",rs.getString(3));
                        break;
                   }
                   else {
                       HttpSession session = request.getSession();
                        session.setAttribute("usernam","");
                   }
               }
               if(flog==true){
                        response.sendRedirect("index.jsp"); //登陆成功，到主页去了
                 }
               else{
                      RequestDispatcher dispatcher =
                               getServletConfig().getServletContext().getRequestDispatcher("/loginWrong.jsp");//页面改一下
                       dispatcher.forward(request, response);
                   } 
                
              }catch(SQLException e) {
                   System.out.println(e.toString());
              }finally{
                  if(rs!=null)try{rs.close();}catch(java.sql.SQLException e1){
                      System.out.println(e1.toString());
                  }finally{
                      try{
                          if(st!=null)
                              st.close();
                      }catch(java.sql.SQLException e2){
                        System.out.println(e2.toString());
                      }finally{
                          try{
                              if(conn!=null)conn.close();
                          }catch(java.sql.SQLException e3){
                                System.out.println(e3.toString());
                          }
                      }
                  }
              }
             
       
	}

protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
            response.setContentType("text/html;charset=GB2312");
            request.setCharacterEncoding("gb2312");
            try {
                processRequest(request,response);
            } catch (Exception ex) {
                Logger.getLogger(LoginCheck.class.getName()).log(Level.SEVERE, null, ex);
            }
	}
protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
	//TODO Method stub generated by Lomboz
       response.setContentType("text/html;charset=GB2312");
      request.setCharacterEncoding("gb2312");
                 try{
		processRequest(request,response);
                 }catch(Exception e){
	     }
                  
		
}
 public String getServletInfo(){
       return "Short description";
}
}